---
- name: Install r1soft agent
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Created a Repository
      copy:
        src: r1soft.repo
        dest: /etc/yum.repos.d/r1soft.repo

    - name: Install r1soft agent
      package:
        name: serverbackup-enterprise-agent
        state: present
      notify: R1SOFT_INSTALLED_ON_CENTOS_7

    - name: Power off iptables
      systemd:
        name: firewalld
        state: stopped
      ignore_errors: true

    - name: Get key
      shell: "r1soft-setup --get-key http://backup.parvizmansurov.com"

    - name: Start R1soft agent
      systemd:
        name: sbm-agent
        state: restarted