---
- name: Adds user with ssh key
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Add 1 user
      user:
        name: "{{bob}}"
        generate_ssh_key: true
        state: present
    - name: Create authorized_key file
      file:
        path: "/home/{{bob}}/.ssh/authorized_keys"
        mode: 0600
        state: touch
        owner: "{{bob}}"

    - name:  add public key
      lineinfile:
        path: "/home/{{bob}}/.ssh/authorized_keys"
        line: "{{line}}"