---
- name: add several users
  hosts: localhost
  become: true
  become_method: sudo
  ignore_errors: true
  user:
    name: "{{ item }}"
    state: present
    groups: "wheel"
  loop:
     - ben
     - lisa
     - katty
     - bob