- name: Created a Repository
  copy:
    src: r1soft.repo
    dest: /etc/yum.repos.d/r1soft.repo

- name: Install r1soft agent
  package:
    name: serverbackup-enterprise-agent
    state: present
  notify: R1soft RESTART

- name: Power off iptables
  systemd:
    name: firewalld
    state: stopped
  ignore_errors: true

- name: Get key
  shell: "r1soft-setup --get-key http://18.204.152.10/"


